<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Permisos del panel: dashboard, roles, usuarios, catálogos (incl. cuentas contables), etc.
     * Se asignan todos a superadmin y admin. El modal de permisos (roles) usa PERMISSION_TREE en el front.
     */
    private const PERMISSIONS = [
        'dashboard.view',
        'roles.view',
        'roles.create',
        'roles.update',
        'roles.delete',
        'permissions.view',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'users.restore',
        'users.configure',
        'zonals.view',
        'zonals.create',
        'zonals.update',
        'zonals.delete',
        'offices.view',
        'offices.create',
        'offices.update',
        'offices.delete',
        'warehouses.view',
        'warehouses.create',
        'warehouses.update',
        'warehouses.delete',
        'warehouse_locations.view',
        'warehouse_locations.create',
        'warehouse_locations.update',
        'warehouse_locations.delete',
        'repair_shops.view',
        'repair_shops.create',
        'repair_shops.update',
        'repair_shops.delete',
        'repair_tickets.view',
        'repair_tickets.create',
        'repair_tickets.update',
        'repair_tickets.delete',
        'repair_tickets.approve',
        'repair_tickets.cancel',
        'repair_tickets.configure',
        'repair_tickets.export',
        'departments.view',
        'departments.create',
        'departments.update',
        'departments.delete',
        'gl_accounts.view',
        'gl_accounts.create',
        'gl_accounts.update',
        'gl_accounts.delete',
        'asset_categories.view',
        'asset_categories.create',
        'asset_categories.update',
        'asset_categories.delete',
        'asset_subcategories.view',
        'asset_subcategories.create',
        'asset_subcategories.update',
        'asset_subcategories.delete',
        'asset_brands.view',
        'asset_brands.create',
        'asset_brands.update',
        'asset_brands.delete',
        'asset_models.view',
        'asset_models.create',
        'asset_models.update',
        'asset_models.delete',
        'component_types.view',
        'component_types.create',
        'component_types.update',
        'component_types.delete',
        'suppliers.view',
        'suppliers.create',
        'suppliers.update',
        'suppliers.delete',
        'purchase_orders.view',
        'purchase_orders.view_detail',
        'purchase_orders.create',
        'purchase_orders.update',
        'purchase_orders.delete',
        'purchase_orders.approve',
        'purchase_orders.export',
        'purchase_orders.observe',
        'purchase_quotes.view',
        'purchase_quotes.create',
        'purchase_quotes.delete',
        'purchase_quotes.select',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'invoices.delete',
        'invoices.status',
        'stock_entries.view',
        'stock_entries.create',
        'stock_entries.items.create',
        'stock_entries.items.update',
        'stock_entries.items.delete',
        'stock_entries.save',
        'stock_entries.delete',
        'assets.view',
        'assets.create',
        'assets.update',
        'assets.delete',
        'assets.configure',
        'assets.barcodes.view',
        'assets.barcodes.bulk',
        'assets.export',
        'components.view',
        'components.create',
        'components.update',
        'components.delete',
        'components.configure',
        'components.barcodes.view',
        'components.barcodes.bulk',
        'components.export',
        'services.view',
        'services.create',
        'services.update',
        'services.delete',
        'asset_transfers.view',
        'asset_transfers.view_detail',
        'asset_transfers.create',
        'asset_transfers.update',
        'asset_transfers.delete',
        'asset_transfers.approve',
        'asset_transfers.cancel',
        'asset_transfers.dispatch',
        'asset_transfers.receive',
        'asset_transfers.export',
        'asset_disposals.view',
        'asset_disposals.create',
        'asset_disposals.approve',
        'asset_disposals.reject',
        'asset_disposals.delete',
        'asset_disposals.export',
        'asset_disposals.sale',
        'asset_disposals.sale.approve',
        'asset_disposals.sale.reject',
        'asset_disposals.sale.delete',
        'preventive_plans.view',
        'preventive_plans.create',
        'preventive_plans.update',
        'preventive_plans.delete',
        'preventive_tasks.view',
        'preventive_tasks.create',
        'preventive_tasks.update',
        'preventive_tasks.delete',
        'inventory_counts.view',
        'inventory_counts.create',
        'inventory_counts.update',
        'inventory_counts.delete',
        'inventory_counts.view_items',
        'inventory_counts.scan',
        'inventory_counts.reconcile',
        'inventory_counts.close',
        'inventory_counts.export',
        'alerts.view',
        'depreciation.view',
        'depreciation.create',
        'depreciation.update',
        'depreciation.delete',
        'depreciation.approve',
    ];

    public function run(): void
    {
        foreach (self::PERMISSIONS as $name) {
            Permission::firstOrCreate(
                ['name' => $name, 'guard_name' => 'web']
            );
        }

        $superadmin = Role::query()->where('name', 'superadmin')->where('guard_name', 'web')->first();
        if ($superadmin instanceof Role) {
            $superadmin->syncPermissions(self::PERMISSIONS);
        }

        $admin = Role::query()->where('name', 'admin')->where('guard_name', 'web')->first();
        if ($admin instanceof Role) {
            $admin->syncPermissions(self::PERMISSIONS);
        }
    }
}
